### ISSUE TITLE
Remove the extra space added in the aid station time

### ISSUE THREAD

**Issue by FJBDev** [patrovite/Course_Generator#105]
![screenshot from 2018-08-25 16-22-40](https://user-images.githubusercontent.com/25235665/44623085-55e42f80-a883-11e8-9cbf-1f8518ef8f0b.png)

**Comment by FJBDev** [comment]
- [ ] Coding
- [ ] Tests
- [ ] Documentation

**Comment by patrovite** [comment]
Please check "tests" if you did tests and check "documentation" if you wrote the documentation or if no documentation is needed.
