### ISSUE TITLE
For a given course and date, display the last 3 years of weather data

### ISSUE THREAD

**Issue by FJBDev** [patrovite/Course_Generator#108]
On top of the map (or elsewhere), display the weather data for the X previous years (with X being defined by the user)
The weather data could contain the following information : 
daily averaged temperature
daily min temperature
daily max temperature
night temperature
Moon phase
Precipitation

~~Use the OpenWeatherMap API : https://openweathermap.org/history~~ (This service is not free)
~~Use [Dark Sky API](https://darksky.net/dev) : The user can get an API key and the API offers *1,000 Calls Per Day for Free*~~ This service would require CG to have 1 API key for each request that any user makes, which would make this service a non-free service.
The [NOAA API](https://www.ncdc.noaa.gov/cdo-web/webservices/v2) was chosen as it is 100% free (https://www.ncdc.noaa.gov/cdo-web/token) _"An access token is required to use the API, and each token will be **limited to five requests per second and 10,000 requests per day**."_

~~Technical questions : ~~
~~ - Can JXMapviewer 2 display widgets ? or should we display the weather info on a menu that can be hidden by the user ?~~

**Comment by patrovite** [comment]
With JXMapviewer you add an image over the tiles. I didn't test if it's possible to add a text over map. Probably.
Another solution is to generate an image with all the informations and to add it on the map.

**Comment by FJBDev** [comment]
Or we could add a small window on the side with the weather data in it ?
![untitled](https://user-images.githubusercontent.com/25235665/44851075-63e7d680-ac1c-11e8-855b-a2667909aecb.png)

**Comment by FJBDev** [comment]
And maybe add a "weather effect" ? Like the altitude effect that will slow down a runner, hot or very cold temperatures could slow down the pace as well ?

**Comment by patrovite** [comment]
Why not adding a tab "weather" with the "old" data and has you proposed a "weather effect" that will impact all the track?

**Comment by FJBDev** [comment]
Good idea, or maybe adding a Weather section in the "Statistics" tab ?

**Comment by patrovite** [comment]
Yes. Good idea. This involve less coding...

**Comment by FJBDev** [comment]
* [x] Coding
* [x] Tests
* [x] Documentation
