### ISSUE TITLE
Issues when downloading OpenStreetMap and OpenTopoMap tiles

### ISSUE THREAD

**Issue by FJBDev** [patrovite/Course_Generator#109]
Failed loading https://a.tile.opentopomap.org/16/11682/23530.png: https://a.tile.opentopomap.org/16/11682/23530.png
Failed loading https://c.tile.opentopomap.org/16/11684/23530.png: https://c.tile.opentopomap.org/16/11684/23530.png
Failed loading https://b.tile.opentopomap.org/16/11683/23530.png: https://b.tile.opentopomap.org/16/11683/23530.png
Failed loading https://a.tile.opentopomap.org/16/11684/23532.png: https://b.tile.opentopomap.org/16/11684/23532.png
Failed loading https://c.tile.opentopomap.org/16/11684/23531.png: https://a.tile.opentopomap.org/16/11684/23531.png
Failed loading https://b.tile.opentopomap.org/16/11683/23531.png: https://b.tile.opentopomap.org/16/11683/23531.png
Failed loading https://a.tile.opentopomap.org/16/11682/23531.png: https://c.tile.opentopomap.org/16/11682/23531.png
Failed loading https://c.tile.opentopomap.org/16/11683/23532.png: https://c.tile.opentopomap.org/16/11683/23532.png
Failed loading https://b.tile.opentopomap.org/16/11682/23532.png: https://b.tile.opentopomap.org/16/11682/23532.png
Failed loading https://a.tile.opentopomap.org/16/11681/23532.png: https://a.tile.opentopomap.org/16/11681/23532.png
Failed loading https://a.tile.opentopomap.org/16/11681/23530.png: https://b.tile.opentopomap.org/16/11681/23530.png
Failed loading https://b.tile.opentopomap.org/16/11681/23531.png: https://c.tile.opentopomap.org/16/11681/23531.png
Failed loading https://a.tile.opentopomap.org/16/11685/23531.png: https://c.tile.opentopomap.org/16/11685/23531.png
Failed loading https://c.tile.opentopomap.org/16/11685/23532.png: https://b.tile.opentopomap.org/16/11685/23532.png
Failed loading https://b.tile.opentopomap.org/16/11685/23530.png: https://a.tile.opentopomap.org/16/11685/23530.png

**Comment by patrovite** [comment]
A bug in JXMapviewer 2 widget or in the class we implemented for opentopomap.

**Comment by FJBDev** [comment]
Do you see this issue on your computer too ? or is it only me ?

**Comment by patrovite** [comment]
I modified the message. Now the message is "Failed loading tile at url = xxxxxx - Message: xxxxx"
Temporally I added a debug message to check if the url was good. During the test the url was good and the message seem to appear when the cache system is not able to download the tile.
The message appear due to a server timeout or not reachable.

**Comment by patrovite** [comment]
Fixed
