### ISSUE TITLE
Uses wrong altitude values instead of simply using those from the GPX track

### ISSUE THREAD

**Issue by cperrier** [patrovite/Course_Generator#156]
When importing A GPX file, it seems that CG "corrects" altitude data with values from the underlying map (OpenTopoMap for instance).

It may lead to very wrong values when the track is very close to a cliff. I noticed that while working on the UT Vercors 2019 track (I'll attach the relevant GPX file)

**Comment by cperrier** [comment]
I can't attach the GPX file, but you'll find it here : https://drive.google.com/open?id=1iUjns_TqFY11bkS9vpM5adaN6TD8tSNx

When imported, just go close to point #7000 (La Grande Sure). You'll find that instead of being at 1640m altitude, the path drops to 1450m very quickly, just because CG "thinks" that the path jumps over the cliff...:-)

I would indeed expect an option that would NOT correct altitudes in the imported GPX file, which would avoid such artefacts.

**Comment by patrovite** [comment]
Hello,
CG doesn't correct the elevation.
At line number 7006 (lat=45.23515 lon=5.59789) the elevation is 1450 in the data grid and also in the gpx file.
Bellow is content of the gpx file for this position.

<trkpt lat="45.23515" lon="5.59789">
        <ele>1450</ele>
        <time>2010-01-01T07:06:41Z</time>
</trkpt>

If 1640m it's the right elevation this mean that it's problem that occur during the creation of the track.
2 solutions:
* you edit the position and you correct manually the elevation 
* you use https://www.gpsvisualizer.com/ to correct the elevations of the track

You can also reduce the number of positions. 8332 position for 96km it's too much.

**Comment by cperrier** [comment]
You're right, Pierre. I was confident in the race's "official" GPX track and I was wrong. I suppose they haven't use a track that comes out of a barometric GPS device, but probably that they "normalized" altitude data with an online tool. If the points accuracy is slightly wrong by a few meters (or the online tool's data), then you end up on one side or another of the Vercors cliffs......and they're very high.

There's a similar artefact at another place in the GPX data.

Filtering out points when importing isn't enough : the artefact is still there. I suspect that correcting elevations will also fail because it's probably what created the problem....

**Comment by cperrier** [comment]
After more checks, I confirm that the problem doesn't lie in CG. Smoothing elevation data rin the imported GPX file removes the artefact.

I hereby close this (non) issue Thanks for your answer, Pierre.
