### ISSUE TITLE
Définir des courbes de difficultés en fonction de pourcentage de D+

### ISSUE THREAD

**Issue by Karno35** [patrovite/Course_Generator#168]
Bonjour Pierre,

Je trouve que cela faciliterait beaucoup le travail de préparation de sa trace si on pouvait paramétrer dans une option, qu'une pente comprise entre 0 et 7% par exemple, on considère cela comme Très facile et ainsi de suite

Bon courage pour la suite

Cordialement 

Arno

**Comment by patrovite** [comment]
Bonjour,

Je ne comprends pas ta demande. Actuellement la pente est prise en compte dans les calculs. C'est la courbe "Vitesse/Pente" qui joue ce rôle.

Pierre

**Comment by Karno35** [comment]
Bonjour Pierre,

Quand je commence a bosser sur ma nouvelle trace voici comment je procède
1 / Chargement de la trace GPX
2 / Je parcours via l'onglet Donnée, les variations de terrain pour leur affecter une difficulté de parcours

Et c'est cette étape (je pense) qui pourrait être facilitée avec la proposition
Proposition
Paramétrer dans la fenetre (colonne difficulté du parcours) que les pentes très difficiles sont > 30  % , difficiles > 15%, cela faciliterait le travail sur l'affectation des notions de difficultés. 

Mais je commence à prendre en main ton logiciel et il a pleins de ressources, c'est génial

Merci 
Arno

**Comment by patrovite** [comment]
La difficulté du terrain vu par CG n'est pas lié à la pente.
Si tu as fait la Saintélyon, la montée de Beaunant est une montée sur route raide mais pas difficile au sens difficulté du terrain. Par contre, tu as des passages en montages dans des pierriers où tu as 0% de pente, mais tu avances en marchant.

De plus si ton parcours est enregistré avec un GPS qui enregistre à la seconde. Tu vas très vite avoir une très grosse densité de points et la moindre bosse vas avoir te faire apparaitre de forte pente. C'est encore pire si ton GPS gère mal la mesure d'altitude.

Lorsque je prends commence un nouveau parcours je rempli d'abord le parcours avec une valeur moyenne de la difficulté puis le modifie par tronçon.
Pour la Saintélyon, je mets tout le parcours en "Facile". Puis je mets les sections de route en "Très facile" et enfin certaines parties en moyen.

**Comment by Karno35** [comment]
ca marche , je capte 
Merci pour tes retours
