### ISSUE TITLE
Use Thunderforest tiles

### ISSUE THREAD

**Issue by patrovite** [patrovite/Course_Generator#37]
If possible, add the outdoors thunderforest tiles (http://thunderforest.com/).
api key need by the user because it can't inserted directly in the application.

Need to see with the website if we are allowed (see terms and conditions).

**Comment by FJBDev** [comment]
That's a good idea as it seems that the map option is a bit limited as of today.

**Comment by FJBDev** [comment]
Ok, I can see that Google Maps has done the same actually. Personally, I dont want to enter a key but it must be just me. 
Let's implement that!

**Comment by FJBDev** [comment]
- [x] Coding
- [] Tests
- [] Documentation
