### ISSUE TITLE
4K and ultrawide support.

### ISSUE THREAD

**Issue by BDafflon** [patrovite/Course_Generator#61]
Add an option to make texts and icons readable on ultrawide and 4K display screen

**Comment by patrovite** [comment]
In the Global settings I added a font setting option. You can now choose the font family, style and size.
This doesn't change the icons size :( I added an "enhancement" issue for this.

**Comment by patrovite** [comment]
Todo list:
- [x] Modifications
- [x] Tests
- [ ] Documentation

**Comment by patrovite** [comment]
Done. In the software settings you can adjust the size of the font and the size of different type of icons.
