### ISSUE TITLE
Generate curves in miles/h

### ISSUE THREAD

**Issue by patrovite** [patrovite/Course_Generator#68]
Generate curves in miles/h

**Comment by patrovite** [comment]
Not in miles/h but in pace

**Comment by patrovite** [comment]
I added a menu in order to copy the curves from the resource to the config folder. Otherwise the new files are not seen in the curves dialog.

**Comment by patrovite** [comment]
If it's finished, please close the issue.

**Comment by FJBDev** [comment]
I will close it soon but I still need to copy the curve files into the installer
