### ISSUE TITLE
Review english translation

### ISSUE THREAD

**Issue by patrovite** [patrovite/Course_Generator#8]
I did the translation but it's not perfect. A review of "Bundle.properties" and "Bundle_en_US.properties" would be great.

**Comment by m4mukulgarg** [comment]
Could you point to the files?

**Comment by patrovite** [comment]
/src/course_generator/

**Comment by m4mukulgarg** [comment]
I'm supposed to review the comments, right?

**Comment by patrovite** [comment]
No. Inside the 2 files ("Bundle.properties" and "Bundle_en_US.properties") you have the english translation. The format of the file is :
label = text

example :  
frmMain.mnuMarkPosition.text=Mark the current position
Don't change the "label"  (frmMain.mnuMarkPosition.text) check only the right part after the "=".

The 2 files should also have the same translation. If you system language is not found (for example spanish) the system read the content of "Bundle.properties".

Currently there is 3 files :
- "Bundle.properties"  : default file (English)
- "Bundle_en_US.properties" : English/US translation file
- "Bundle_fr_FR.properties" : French translation file

Is ok for you?

**Comment by m4mukulgarg** [comment]
Ok! Let me make a pull request. I hope there isn't a deadline...

**Comment by patrovite** [comment]
No. Just review the English translate. It has been done by me. It's not perfect.

**Comment by m4mukulgarg** [comment]
I'm Sorry, but I don't speak French.

**Comment by FJBDev** [comment]
@patrovite I will take care of it
