### ISSUE TITLE
Add icons for "Drop bag" and "crew"

### ISSUE THREAD

**Issue by FJBDev** [patrovite/Course_Generator#95]

**Comment by FJBDev** [comment]
Did I dream or the "drop bag" or "backpack" icon was in the C# version 3.X ?

**Comment by patrovite** [comment]
Yes! it was present :)

**Comment by patrovite** [comment]
I had tags for "drop bag", "crew" and "first aid". Documentation updated in french and english.

**Comment by FJBDev** [comment]
Tip when committing for a specific Issue : 
In the commit message, reference the Issue number  (in this case, it would be #95). That way, the commit gets automatically added to the issue. 
Example with one of my recent issue : 
![untitled2](https://user-images.githubusercontent.com/25235665/44372886-55265480-a4a3-11e8-92ed-f6e62f98db9e.png)
