### ISSUE TITLE
Curve file without 'km_h' or 'mile' not shown in the curve list

### ISSUE THREAD

**Issue by patrovite** [patrovite/Course_Generator#96]
In V4.1 a unit has been added to filter filter curves in km/h and mile.
If the user create a curve (for example from a GPX file) and don't include 'mile' or 'km_'h, the curve doesn't appear in the curve list.

**Comment by patrovite** [comment]
TODO:
Remove the filter or if the 'km_h' or 'mile' isn't included in the filename then add the file to the list.

**Comment by FJBDev** [comment]
Correct, I realized that before 4.1 and I had created a Pull Request for it (https://github.com/patrovite/Course_Generator/pull/94/files) but it never was merged or accepted in 4.1. 4.2 then ?

**Comment by FJBDev** [comment]
I just thought that displaying the min/mile curves for a user using the metric km/m unit would be useless, what do you think ?

**Comment by patrovite** [comment]
Your idea was not bad. The only problem its that it doesn't take into account that users can create curves that doesn't have mile or km_h in the file name.
May be it's time to take our time and think to a good solution.
For example to a file name with fix part which will be set by the software and a part which be set by the user.
KM_H-10.5-Run.par => [Unit]-[Value]-[Description].par
[Unit]=> KM_H/ MIN_MILE/MIN_KM => Set by the software when it's saved
[Value]=> Set by the software when it's saved 
[Description]=>Set by the user when it's saved

We need to create a special save dialog where the user can:
* Select the unit with radio boxes => [Unit]
* Enter the "speed" => [value]
* Enter the description => [Description]
With these information the software can generate the file name.

In the curve dialog we can add a unit display filter (check boxes).

Other solutions?

**Comment by FJBDev** [comment]
That's a possibility. However, I don't like forcing the user to name a file following a convention, I think it's better that the user is free to enter what he/she wants.
What if we create a directory for the software curves and one for the user curves. That way we know which curves to filter out and which ones not to filter out ?
For example : 
.course_generator/curves/internal/ (all the software curves)
.course_generator/curves/user/(all the user curves)

**Comment by FJBDev** [comment]
I am thinking that we should only put the default curves in a separate directory. That way, the user won't have to move the already created curves to a specific folder.
In the end, it would look like this : 
.course_generator/curves/internal/ (all the software curves)
.course_generator/curves/(all the user curves)

Are you doing this ? or do you want me to do this ?
