### ISSUE TITLE
For the sections to be traveled during nighttime, display a gray halo around the track

### ISSUE THREAD

**Issue by FJBDev** [patrovite/Course_Generator#98]
Displaying the night time on the mini road book is great, but displaying it on the map is even better !
To Check : Is it possible within the current track display API ?

Example (rough idea done manually) :
![untitled](https://user-images.githubusercontent.com/25235665/43746299-b2ecf118-99a0-11e8-92d4-d5c0f16bc600.png)

**Comment by patrovite** [comment]
I think it's possible. Not easy but possible.

**Comment by patrovite** [comment]
* [x] code
* [x] tests
* [x] documentation
